upstream api_gateway {
    server clase-arquitectura-api_gateway-1:5000;
    server clase-arquitectura-api_gateway-2:5000;
}

server {
    listen 3000;

    location / {
        proxy_pass http://api_gateway;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
